name: First workflow
on: workflow_dispatch
jobs:
  fristJob:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello wrold"
      - name: Print goodbye
        run: echo "Done-by"
      
